import { useState } from 'react';
import { ChevronDown, ChevronUp, Search, Database, Users, Target } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import SEOHead from '@/components/SEOHead';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function FAQPage() {
  const [openFAQ, setOpenFAQ] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenFAQ(openFAQ === index ? null : index);
  };

  const faqs = [
    {
      category: "About ELP Data",
      questions: [
        {
          question: "What is ELP Data?",
          answer: "ELP Data is the most comprehensive technology data and business intelligence platform covering enterprise implementations, decision makers, and market intelligence. We provide verified contact databases, technology installation data, and real-time intelligence across 1000+ business software applications to help B2B companies identify and connect with their ideal prospects."
        },
        {
          question: "What makes ELP Data different from other data providers?",
          answer: "ELP Data offers 99.2% data accuracy vs industry average of 60-70%, real-time technology intelligence across 1000+ software platforms, A++ verified contacts with email validation and phone verification, and proprietary AI-powered web crawling technology. We specialize specifically in technology intelligence rather than generic business data."
        },
        {
          question: "How accurate is ELP Data's contact information?",
          answer: "Our contact data maintains 99.2% email accuracy and 97.8% phone verification rates. Every contact undergoes multi-layer verification including email validation, phone verification, communication approval status, and recent activity confirmation. This ensures maximum deliverability for your outreach campaigns."
        }
      ]
    },
    {
      category: "Data & Technology Intelligence",
      questions: [
        {
          question: "What is data enrichment in MDM?",
          answer: "Data enrichment in Master Data Management (MDM) is the process of enhancing existing customer records with additional verified information from external sources. This includes adding missing contact details, company information, technology stack data, and behavioral insights to create complete customer profiles for better targeting and personalization."
        },
        {
          question: "What is ETL in data?",
          answer: "ETL stands for Extract, Transform, Load - a data integration process that extracts data from various sources, transforms it into a consistent format, and loads it into a target system like a data warehouse. In business intelligence, ETL processes ensure clean, standardized data for analytics and reporting."
        },
        {
          question: "What is digital data in BDA?",
          answer: "Digital data in Big Data Analytics (BDA) refers to electronic information generated by digital interactions, transactions, and behaviors. This includes website analytics, social media engagement, email interactions, software usage patterns, and digital touchpoints that provide insights into customer behavior and business performance."
        },
        {
          question: "How does ELP Data collect technology intelligence?",
          answer: "We use proprietary AI-powered web crawlers that analyze over 50 million corporate websites, identifying technology footprints through code analysis, job postings, technical documentation, and integration patterns. Our multi-layer verification system cross-references this data with SEC filings, vendor announcements, and partnership data for 99.2% accuracy."
        }
      ]
    },
    {
      category: "Business Intelligence & Analytics",
      questions: [
        {
          question: "What is a business intelligence platform?",
          answer: "A business intelligence platform is a comprehensive solution that collects, processes, and analyzes business data to provide actionable insights for decision-making. ELP Data's platform specifically focuses on technology intelligence, providing insights into software implementations, market trends, and competitive intelligence across enterprise technology landscapes."
        },
        {
          question: "How can technology data improve sales performance?",
          answer: "Technology data enables precise prospect targeting by identifying companies using specific software solutions, timing outreach during technology transitions, personalizing messaging based on current technology stack, and reducing sales cycles through better qualification. Our clients typically see 45-67% improvement in response rates using targeted technology intelligence."
        },
        {
          question: "What types of technology intelligence does ELP Data provide?",
          answer: "We cover 1000+ business software applications including ERP systems (SAP, Oracle, Microsoft), CRM platforms (Salesforce, HubSpot), cloud infrastructure (AWS, Azure), database management systems, marketing automation tools, HR software, manufacturing systems, healthcare technologies, and emerging AI/ML platforms."
        }
      ]
    },
    {
      category: "Implementation & Integration",
      questions: [
        {
          question: "How quickly can I access ELP Data intelligence?",
          answer: "Most standard data requests are fulfilled within 24-48 hours. Custom intelligence projects and large-scale data compilations typically take 5-10 business days. Our real-time API provides instant access to core technology intelligence and contact verification services."
        },
        {
          question: "Can ELP Data integrate with my existing CRM system?",
          answer: "Yes, we provide seamless integrations with major CRM platforms including Salesforce, HubSpot, Microsoft Dynamics, Pipedrive, and custom systems via API. Our integration ensures real-time data synchronization and automated lead enrichment workflows."
        },
        {
          question: "What data formats does ELP Data provide?",
          answer: "We deliver data in multiple formats including CSV/Excel files, JSON for API integration, direct CRM uploads, and custom formats based on your requirements. All exports include data dictionaries and field explanations for easy implementation."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-white">
      <SEOHead 
        title="FAQ - Technology Data & Business Intelligence Questions | ELP Data"
        description="Get answers about ELP Data's technology intelligence platform, data enrichment, ETL processes, business intelligence, and how our verified contact database can improve your B2B sales performance."
        keywords="what is ELP data, data enrichment MDM, ETL data, digital data BDA, business intelligence platform, technology intelligence, B2B data, contact verification"
      />
      <Header />
      
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-blue-900 via-indigo-800 to-purple-900 text-white py-20">
        <div className="max-w-7xl mx-auto px-6 text-center">
          <Badge className="bg-white/20 text-white border-0 px-6 py-3 text-lg font-semibold mb-8">
            Frequently Asked Questions
          </Badge>
          <h1 className="text-5xl md:text-6xl font-bold mb-8 leading-tight">
            <span className="bg-gradient-to-r from-white via-blue-100 to-purple-200 bg-clip-text text-transparent">
              Everything You Need to Know
            </span>
            <br />
            <span className="text-white">About ELP Data</span>
          </h1>
          <p className="text-xl md:text-2xl text-blue-100 mb-12 max-w-4xl mx-auto leading-relaxed">
            Get instant answers about technology intelligence, data enrichment, business intelligence platforms, 
            and how ELP Data can transform your B2B sales and marketing performance.
          </p>
          
          {/* Search Bar */}
          <div className="max-w-2xl mx-auto">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <input
                type="text"
                placeholder="Search FAQ topics like 'data enrichment', 'technology intelligence', 'contact verification'..."
                className="w-full pl-12 pr-4 py-4 bg-white/10 backdrop-blur-xl border border-white/20 rounded-xl text-white placeholder-gray-300 focus:ring-2 focus:ring-blue-400 focus:border-transparent"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Quick Stats */}
      <section className="py-16 bg-gradient-to-br from-slate-50 to-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid md:grid-cols-4 gap-8 text-center">
            <div className="bg-white p-6 rounded-2xl shadow-lg border-2 border-blue-100">
              <Database className="w-12 h-12 text-blue-600 mx-auto mb-4" />
              <div className="text-3xl font-bold text-blue-600 mb-2">1000+</div>
              <p className="text-slate-600">Technology Platforms Covered</p>
            </div>
            
            <div className="bg-white p-6 rounded-2xl shadow-lg border-2 border-emerald-100">
              <Users className="w-12 h-12 text-emerald-600 mx-auto mb-4" />
              <div className="text-3xl font-bold text-emerald-600 mb-2">99.2%</div>
              <p className="text-slate-600">Contact Data Accuracy</p>
            </div>
            
            <div className="bg-white p-6 rounded-2xl shadow-lg border-2 border-purple-100">
              <Target className="w-12 h-12 text-purple-600 mx-auto mb-4" />
              <div className="text-3xl font-bold text-purple-600 mb-2">50M+</div>
              <p className="text-slate-600">Corporate Websites Analyzed</p>
            </div>
            
            <div className="bg-white p-6 rounded-2xl shadow-lg border-2 border-orange-100">
              <Search className="w-12 h-12 text-orange-600 mx-auto mb-4" />
              <div className="text-3xl font-bold text-orange-600 mb-2">24hrs</div>
              <p className="text-slate-600">Average Data Delivery</p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Sections */}
      <section className="py-20 bg-white">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-slate-900 mb-6">Common Questions About Technology Intelligence</h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              Find answers to the most frequently asked questions about data enrichment, business intelligence platforms, 
              and how ELP Data's technology intelligence can accelerate your growth.
            </p>
          </div>

          <div className="space-y-12">
            {faqs.map((category, categoryIndex) => (
              <div key={categoryIndex} className="bg-gradient-to-br from-slate-50 to-white rounded-2xl p-8 shadow-lg">
                <h3 className="text-2xl font-bold text-slate-900 mb-8 flex items-center">
                  <div className="w-2 h-8 bg-gradient-to-b from-blue-500 to-purple-600 rounded-full mr-4"></div>
                  {category.category}
                </h3>
                
                <div className="space-y-6">
                  {category.questions.map((faq, faqIndex) => {
                    const globalIndex = categoryIndex * 10 + faqIndex;
                    return (
                      <Card key={faqIndex} className="bg-white border-2 border-slate-200 rounded-xl shadow-sm hover:shadow-lg transition-all duration-300">
                        <div 
                          className="p-6 cursor-pointer flex items-center justify-between"
                          onClick={() => toggleFAQ(globalIndex)}
                        >
                          <h4 className="text-lg font-semibold text-slate-900 pr-4">{faq.question}</h4>
                          {openFAQ === globalIndex ? (
                            <ChevronUp className="w-5 h-5 text-blue-600 flex-shrink-0" />
                          ) : (
                            <ChevronDown className="w-5 h-5 text-slate-400 flex-shrink-0" />
                          )}
                        </div>
                        
                        {openFAQ === globalIndex && (
                          <div className="px-6 pb-6">
                            <div className="border-t border-slate-100 pt-6">
                              <p className="text-slate-700 leading-relaxed">{faq.answer}</p>
                            </div>
                          </div>
                        )}
                      </Card>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Call to Action */}
      <section className="py-16 bg-gradient-to-r from-slate-900 to-slate-800 text-white">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold mb-6">Still Have Questions?</h2>
          <p className="text-xl mb-8 text-slate-300">
            Our technology intelligence experts are ready to help you find the perfect data solution for your business needs.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <button className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-4 rounded-xl font-semibold text-lg transition-colors">
              Schedule a Consultation
            </button>
            <button className="border-2 border-white text-white px-8 py-4 rounded-xl font-semibold text-lg hover:bg-white hover:text-slate-900 transition-colors">
              Contact Our Experts
            </button>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}